In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

# cap = cv2.VideoCapture(0)
# while(1):
#     # 获得图片
#     ret, frame = cap.read()
#     # 展示图片
#     cv2.imshow("capture", frame)
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         # 存储图片
#         cv2.imwrite("red.jpg", frame)
#         break


image=cv2.imread('1.jpg')
HSV=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
def getpos(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN: #定义一个鼠标左键按下去的事件
        print(HSV[y,x])

cv2.imshow("imageHSV",HSV)
cv2.imshow('image',image)
cv2.setMouseCallback("imageHSV",getpos)
cv2.waitKey(0)
cv2.destroyAllWindows()

[119 255  22]
[121 255  48]
[120 255  47]
[ 72  37 116]
[0 0 0]
[110 255   3]
[ 60 255  10]
[104 200 111]
